katalog/urls.py
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import create_task_json, register, show_json, delete_todo
from todolist.views import login_user
from todolist.views import logout_user 
from todolist.views import show_todolist
from todolist.views import create_task
from todolist.views import update_task
from todolist.views import delete_task


app_name = 'todolist'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_user, name='login_user'),
    path('logout/', logout_user, name='logout_user'),
    path('', show_todolist, name='show_todolist'),  
    path('json/', show_json, name='show_json'),  
    path('create-task/', create_task, name='create_task'),
    path('add/', create_task_json, name='create_task_json'),
    path('delete/<int:id>', delete_todo, name='delete_todo'),
    path('update-task/<int:id>', update_task, name='update_task'),
    path('delete-task/<int:id>', delete_task, name='delete_task'),
    
]

todolist/models.py
from datetime import datetime
from xmlrpc.client import MAXINT, MININT
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User

class Task(models.Model):
    user =  models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(default=datetime.now())
    title =  models.CharField(max_length=255)
    desc =  models.TextField()
    is_finished  = models.BooleanField(default=False)
    

todolist/views.py
from re import I
from django.shortcuts import render
from django.shortcuts import redirect

from django.http import HttpResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.forms import ModelForm
from todolist.models import Task
from datetime import date, datetime

@login_required(login_url='/todolist/login/')
def delete_task(request, id):
    task_list = Task.objects.filter(id=id)
    task = task_list[0]
    task.delete()   
    return redirect('todolist:show_todolist')


@login_required(login_url='/todolist/login/')
def update_task(request, id):
    task_list = Task.objects.filter(id=id)
    task = task_list[0]
    task.is_finished = not task.is_finished
    task.save()
    return redirect('todolist:show_todolist')
    
class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = [
            'title',
            'desc'
        ]

@login_required(login_url='/todolist/login/')
def create_task(request):
    form = TaskForm()
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid:
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            messages.success(request, 'Task telah berhasil dibuat!')
            return redirect('todolist:show_todolist')
    context = {'form':form}
    return render(request, 'create-task.html', context)


@login_required(login_url='/todolist/login/')
def create_task_json(request):
    if request.method == "POST":
        task = Task(
            title = request.POST["title"],
            desc = request.POST["desc"],
            user = request.user,
        )
        task.save()
        return HttpResponse(
            serializers.serialize("json", [task]),
            content_type="application/json",
        )
    return HttpResponse("Invalid method", status_code=405)

@login_required(login_url="/todolist/login")
def delete_todo(request, id):
    print(request.method)
    if request.method == "DELETE":
        task = Task.objects.filter(id=id).first()
        if task:
            task.delete()
            messages.success(request, "Berhasil dihapus!")
        else:
            messages.error(request, "Task tidak ditemukan!")

    return redirect("todolist:show_todolist")

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    context = {
        'username': request.user.username,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def show_json(request):
    tasks = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", tasks), content_type="application/json")

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login_user')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login_user'))
    response.delete_cookie('last_login')
    return response

todolist/templates/create-task.html
{% extends 'base.html' %}

{% block meta %}

<title>Buat Task</title>
{% endblock meta %}

{% block content %}  


<section class=" text-center text-lg-start">
    <style>
      .rounded-t-5 {
        border-top-left-radius: 0.5rem;
        border-top-right-radius: 0.5rem;
      }
  
      @media (min-width: 992px) {
        .rounded-tr-lg-0 {
          border-top-right-radius: 0;
        }
  
        .rounded-bl-lg-5 {
          border-bottom-left-radius: 0.5rem;
        }
      }
    </style>
    <div class="container py-5 h-100">
    <div class="card mb-3 py-0">
      <div class="row g-0 d-flex align-items-center justify-content-center">
        <div class="col-lg-8">
          <div class="card-body py-5 px-md-5">
  
            <form method="POST" action="">
                {% csrf_token %}
                <h1>Buat Task</h1>
              <div class="form-outline mb-4">
                <label class="form-label" for="id_title">Judul</label>
                <input class="form-control" type="text" name="title" maxlength="255" required="" id="id_title">
                {% if form.title.errors %}
                <span class="text-danger">{{ form.title.errors }} </span>
                {% endif %}  
              </div>
  
              <div class="form-outline mb-4">
                <label class="form-label" for="id_desc">Deskripi</label>
                <textarea class="form-control" name="desc" cols="40" rows="10" required="" id="id_desc"></textarea>
                {% if form.desc.errors %}
                <span class="text-danger">{{ form.desc.errors }} </span>
                {% endif %} 
              </div>
              <input type="submit" class="btn btn-primary btn-block mb-4" value="Daftar">  
              <a href="{% url 'todolist:show_todolist' %}" class="btn btn-primary btn-block mb-4">Kembali</a>
              
            </form>
        </div>
          </div>
        </div>
      </div>

    </div>
  </section>
{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}



<!-- Section: Design Block -->
<section class=" text-center text-lg-start">
    <style>
      .rounded-t-5 {
        border-top-left-radius: 0.5rem;
        border-top-right-radius: 0.5rem;
      }
  
      @media (min-width: 992px) {
        .rounded-tr-lg-0 {
          border-top-right-radius: 0;
        }
  
        .rounded-bl-lg-5 {
          border-bottom-left-radius: 0.5rem;
        }
      }
    </style>
    <div class="container py-5 h-100">
    <div class="card mb-3 py-0">
      <div class="row g-0 d-flex align-items-center justify-content-center">
        <div class="col-lg-8">
          <div class="card-body py-5 px-md-5">
  
            <form method="POST" action="">
              <h1>Login</h1>
                {% csrf_token %}
              <div class="form-outline mb-4">
                <label class="form-label" for="form2Example1">Username</label>
                <input type="text" name="username" class="form-control">
              </div>
  
              <!-- Password input -->
              <div class="form-outline mb-4">
                <label class="form-label" for="form2Example2">Password</label>
                <input type="password" name="password" class="form-control">
              </div>
  
              <!-- Submit button -->
              <input type="submit" class="btn btn-primary btn-block mb-4" value="Login">
              <div class="col">
                <!-- Simple link -->
                Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>
              </div>    
              {% if messages %}
              <ul>
                  {% for message in messages %}
                  <span class="text-danger">{{ message }}</span>
                  {% endfor %}
              </ul>
                {% endif %}  
            </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  


<section class=" text-center text-lg-start">
    <style>
      .rounded-t-5 {
        border-top-left-radius: 0.5rem;
        border-top-right-radius: 0.5rem;
      }
  
      @media (min-width: 992px) {
        .rounded-tr-lg-0 {
          border-top-right-radius: 0;
        }
  
        .rounded-bl-lg-5 {
          border-bottom-left-radius: 0.5rem;
        }
      }
    </style>
    <div class="container py-5 h-100">
    <div class="card mb-3 py-0">
      <div class="row g-0 d-flex align-items-center justify-content-center">
        <div class="col-lg-8">
          <div class="card-body py-5 px-md-5">
  
            <form method="POST" action="">
                {% csrf_token %}
                <h1>Buat Akun</h1>
              <!-- Email input -->
              <div class="form-outline mb-4">
                <label class="form-label" for="id_username">Username</label>
                <input class="form-control" type="text" name="username" value="" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" id="id_username" placeholder=" ">
                {% if form.username.errors %}
                <span class="text-danger">{{ form.username.errors }} </span>
                {% endif %}  
              </div>
  
              <!-- Password input -->
              <div class="form-outline mb-4">
                <label class="form-label" for="id_password1">Password</label>
                <input class="form-control" type="password" name="password1" autocomplete="new-password" required="" id="id_password1" aria-autocomplete="list" placeholder=" ">
                {% if form.password1.errors %}
                <span class="text-danger">{{ form.password1.errors }} </span>
                {% endif %} 
              </div>

              <div class="form-outline mb-4">
                <label class="form-label" for="id_password2">Confirm Password</label>
                <input class="form-control" type="password" name="password2" autocomplete="new-password" required="" id="id_password2" aria-autocomplete="list" placeholder=" ">
                {% if form.password2.errors %}
                <span class="text-danger">{{ form.password2.errors }} </span>
                {% endif %} 
              </div>
  
              <input type="submit" class="btn btn-primary btn-block mb-4" value="Daftar">  
              
            </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="#">
        <h1 class="p3">Tugas 4 Assignment PBP/PBD</h1>
    </a>
    <a>
        <div>
            <h4>Nama: </h4>
            <h5>{{username}}</h5>
        </div>
        <a href="{% url 'todolist:logout_user' %}" class="btn btn-primary">Logout</a>
    </a>
</nav>

{% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
{% endif %}  

<!-- Section: Design Block -->
<section class=" text-center text-lg-start">
    <style>
      .rounded-t-5 {
        border-top-left-radius: 0.5rem;
        border-top-right-radius: 0.5rem;
      }
  
      @media (min-width: 992px) {
        .rounded-tr-lg-0 {
          border-top-right-radius: 0;
        }
  
        .rounded-bl-lg-5 {
          border-bottom-left-radius: 0.5rem;
        }
      }
      .card{

        background-repeat: no-repeat;
        background-position: right;
        background-size: 80px;
        transition: transform .5s;
      }
    .card:hover{
        transform: scale(1.05);

    }
  </style>
<div class="container py-5 h-100">
  <div class="card mb-3 py-0">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal">
      Create Task
    </button>
  </div>
</div>
<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="modal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="modalLabel">Buat Task</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="POST" action="" id="daftarTask">
          {% csrf_token %}
          <div class="form-outline mb-4">
            <label class="form-label" for="id_title">Judul</label>
            <input class="form-control" type="text" name="title" maxlength="255" required="" id="id_title">
            {% if form.title.errors %}
            <span class="text-danger">{{ form.title.errors }} </span>
            {% endif %}  
          </div>

          <div class="form-outline mb-4">
            <label class="form-label" for="id_desc">Deskripi</label>
            <textarea class="form-control" name="desc" cols="40" rows="10" required="" id="id_desc"></textarea>
            {% if form.desc.errors %}
            <span class="text-danger">{{ form.desc.errors }} </span>
            {% endif %} 
          </div>
          <input type="submit" class="btn btn-primary btn-block mb-4" value="Daftar" id="daftarBtn">
        </form>
      </div>
    </div>
  </div>
</div>
<div class="container py-5 h-100"></div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" 
  integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
  crossorigin="anonymous">
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
  $(document).ready(() => {
    $("#daftarBtn").click(createTodo)
    onload()
  })

  function onload(){
    var container = document.getElementsByClassName("container py-5 h-100")[1]
    container.innerHTML = ""

    $.get("{% url 'todolist:show_json' %}", function (data) {
    
    data.forEach(element => {
      var card = document.createElement("div")
      card.className = "card mb-3 py-0"
      
      var cardContent = document.createElement("div")
      cardContent.className = "row g-0 d-flex align-items-center justify-content-center"
      
      var cardBody = document.createElement("div")
      cardBody.className = "card-body py-5 px-md-5"
    
      var fields = element.fields
      var title = fields.title
      var date = fields.date
      var desc = fields.desc
      var is_finished = fields.is_finished

      var cardHeader = document.createElement("h2")
      cardHeader.className = "card-title"
      cardHeader.innerHTML = title + " (" + date.substring(0,date.indexOf("T")) + ")" 

      var cardText = document.createElement("p")
      cardText.className = "card-text"
      cardText.innerHTML = desc 
      
      var cardStatus = document.createElement("h5")
      cardStatus.className = "card-text"
      cardStatus.innerHTML = (is_finished) ? 'Sudah' : 'Belum' 

      
      var buttonUpdate = document.createElement("a")
      buttonUpdate.href = "/todolist/update-task/" + element.pk
      buttonUpdate.className = "btn btn-primary"
      buttonUpdate.innerHTML = "Update"

      var buttonHapus = document.createElement("a")
      buttonHapus.setAttribute('onclick', `deleteTask(${element.pk})`);
      buttonHapus.className = "btn btn-primary "
      buttonHapus.innerHTML = "Hapus"

      cardBody.appendChild(cardHeader)
      cardBody.appendChild(cardText)
      cardBody.appendChild(cardStatus)
      cardBody.appendChild(buttonUpdate)
      cardBody.appendChild(buttonHapus)

      cardContent.appendChild(cardBody)
      card.appendChild(cardContent)
      container.appendChild(card)

      document.body.appendChild(container)
      }); 
    })

    
  }
  
  function createTodo(e) {
    e.preventDefault()
     $.ajax({
      type: 'POST',
      url: '/todolist/add/',
      data: $("#daftarTask").serialize(), 
      success: () => {
        $("#modal").modal('hide')
        onload()
      },
      dataType: 'json'
    });
  }
  
    

</script>

</section>
{% endblock content %}

todolist/templates/todolist_json.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="#">
        <h1 class="p3">Tugas 4 Assignment PBP/PBD</h1>
    </a>
    <a>
        <div>
            <h4>Nama: </h4>
            <h5>{{username}}</h5>
        </div>
        <a href="{% url 'todolist:logout_user' %}" class="btn btn-primary">Logout</a>

    </a>
</nav>

{% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
{% endif %}  
<!-- Section: Design Block -->
<section class=" text-center text-lg-start">
    <style>
      .rounded-t-5 {
        border-top-left-radius: 0.5rem;
        border-top-right-radius: 0.5rem;
      }
  
      @media (min-width: 992px) {
        .rounded-tr-lg-0 {
          border-top-right-radius: 0;
        }
  
        .rounded-bl-lg-5 {
          border-bottom-left-radius: 0.5rem;
        }
      }
      .card{

        background-repeat: no-repeat;
        background-position: right;
        background-size: 80px;
        transition: transform .5s;
      }
    .card:hover{
        transform: scale(1.05);

    }


    </style>

    
<div class="container py-5 h-100">
      <div class="card mb-3 py-0">
        <a href="{% url 'todolist:create_task' %}" class="btn btn-primary">Buat Task</a>
    </div>
    
    {% for task in list_task %}
    <div class="card mb-3 py-0 ">
      <div class="row g-0 d-flex align-items-center justify-content-center">
          <div class="card-body py-5 px-md-5">
            <h2 class="card-title">{{task.title}} ({{task.date}})</h2>
                <p class="card-text">{{task.desc}}</p>
                {% if task.is_finished %}
                    <h5 class="card-text">Sudah</h5>
                {% else %}
                    <h5 class="card-text">Belum</h5>
                {% endif %}
            
            <a href="{% url 'todolist:update_task' task.id %}" class="btn btn-primary">Update</a>
            <a href="{% url 'todolist:delete_task' task.id %}" class="btn btn-primary">Hapus</a>
            
        </div>
    </div>
</div>
{% endfor %}
</div>
</div>
</section>
<script type="text/javascript">
  console.log("a")

  var container = document.createElement("div");
  container.classList.add("row", "row-cols-1", "row-cols-md-4", "g-4");

  function getTask() {
      container.innerHTML = "";
      $.get("{% url 'todolist:show_json' %}", function (data) {
          
          $.each(data, function (i, value) {
              // iterate per task

              var field = value.fields;
              console.log("yez",value);

              var col = document.createElement("div");
              col.classList.add("col");

              var card = document.createElement("div");
              card.classList.add("card");
              col.appendChild(card);

              var header = document.createElement("div");
              if (field.is_finished == true) {
                  header.classList.add("card-header", "text-bg-success", "text-center");
                  header.innerHTML = "Completed";
              } else {
                  header.classList.add("card-header", "text-bg-warning", "text-center")
                  header.innerHTML = "Not Yet Completed";
              }

              var body = document.createElement("div");
              body.classList.add("card-body");
              var title = document.createElement("h5");
              title.classList.add("card-title");
              title.innerHTML = field.title;
              var desc = document.createElement("p");
              desc.classList.add("card-text");
              desc.innerHTML = field.description;

              body.appendChild(title);
              body.appendChild(desc);

              var footer = document.createElement("div");
              footer.classList.add("card-footer");

              card.appendChild(header);
              card.appendChild(body);
              card.appendChild(footer);

              var date = document.createElement("small");
              date.classList.add("text-muted", "text-center");
              date.innerHTML = `Created ${field.date}`;

              var updateBtn = document.createElement("a");
              updateBtn.classList.add("btn", "btn-primary", "btn-sm", "text-end");
              updateBtn.innerHTML = "Update";
              updateBtn.href = "/todolist/update_task/" + value.pk + "/";

              var deleteBtn = document.createElement("a");
              deleteBtn.classList.add("btn", "btn-danger", "btn-sm", "text-end");
              deleteBtn.innerHTML = "Delete";
              deleteBtn.setAttribute('onclick', `deleteTask(${value.pk})`);

              footer.appendChild(date);
              footer.appendChild(deleteBtn);
              footer.appendChild(updateBtn);

              container.appendChild(col);
          })

          document.body.appendChild(container)

      })
  }

  function deleteTask(pk) {
      var url = `/todolist/delete/${pk}/`;
      $.ajax({
          url: `/todolist/delete/${pk}/`,
          type: "POST",
          data: {},
          success: function (result) {
              getTask();
          },

          error: function (xhr, resp, text) {
                  console.log("ada error cuy")
                  console.log("url",url)
                  console.log("xhr", xhr)
                  console.log("resp", resp)
                  console.log("text", text)
          }
      });
  }

  $(document).ready(function () {

      // GET
      getTask()

      // POST
      console.log("cretask")
      $("#createTask").submit(function (e) {
          e.preventDefault();
          console.log("oi oi oi")
          var actionurl = e.currentTarget;
          var formJSON = JSON.stringify($("#createTask").serializeJSON());
          console.log("e", e)
          console.log("json", formJSON)
          console.log("actionurl", actionurl)

          $.ajax({
              type: "POST",
              url: "{% url 'todolist:todolist_add' %}",
              data: {
                  data: formJSON,
                  csrfmiddlewaretoken: '{{ csrf_token }}'
              },

              success: function (response) {
                  $(response).each(function (i, value) {
                      
                  });
                  $('#createTask').each(function () {
                      this.reset();
                  });
                  console.log("mantap sukses");
                  getTask();

                  $('#exampleModal').modal('toggle');
              },

              error: function (xhr, resp, text) {
                  console.log("ada error")
                  console.log("xhr", xhr)
                  console.log("resp", resp)
                  console.log("text", text)
              }
          });

      });

  });



</script>
{% endblock content %}